// Detects disposable/temporary email domains
// Confidence weight reflects how certain we are it's disposable

const DISPOSABLE_DOMAINS = new Set([
  // High confidence disposable services
  "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.biz", "guerrillamail.de", "guerrillamail.info",
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmail.net",
  "throwam.com", "throwam.net", "trashmail.com", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.at", "trashmail.io",
  "yopmail.com", "yopmail.fr", "yopmail.net", "cool.fr.nf",
  "jetable.fr.nf", "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj",
  "speed.1s.fr", "courriel.fr.nf", "moncourrier.fr.nf",
  "maildrop.cc", "mailnull.com", "mailnull.net",
  "sharklasers.com", "guerrillamailblock.com", "grr.la",
  "guerrillamail.info", "spam4.me", "spamgourmet.com",
  "spamgourmet.net", "spamgourmet.org", "spamgourmet.com",
  "dispostable.com", "dispostable.net", "dispostable.org",
  "fakeinbox.com", "fakeinbox.net", "fakeinbox.org",
  "mailnesia.com", "mailnull.com", "maildrop.cc",
  "spamspot.com", "spamspot.net",
  "getairmail.com", "filzmail.com", "discard.email",
  "spamfree24.org", "spamfree24.de", "spamfree24.info",
  "spamfree24.biz", "spamfree24.net",
  "bobmail.info", "chammy.info", "devnullmail.com",
  "dispostable.com", "letthemeatspam.com",
  "mailismagic.com", "spamgob.com", "spamgob.net",
  "emailondeck.com", "discardmail.com", "discardmail.de",
  "spamgob.com", "spamtrail.com",
  "33mail.com", "anonymail.net",
  "crazymailing.com", "dingbone.com",
  "easytrashmail.com", "emailfake.com",
  "fakemailgenerator.com", "fakemail.fr",
  "fleckens.hu", "gishpuppy.com",
  "hartbot.de", "hidemail.de",
  "inoutmail.de", "inoutmail.eu", "inoutmail.info", "inoutmail.net",
  "jetable.com", "jetable.de", "jetable.net", "jetable.org",
  "koszmail.pl", "kurzepost.de",
  "lazyinbox.com", "litedrop.com",
  "mailin8r.com", "mailme.lv",
  "netzidiot.de", "nh3.ro",
  "nobulk.com", "noclickemail.com",
  "nogmailspam.info", "nomail.pw",
  "objectmail.com", "obobbo.com", "odnorazovoe.ru",
  "oneoffmail.com", "onewaymail.com",
  "pookmail.com", "proxymail.eu",
  "rcpt.at", "rklips.com", "rmqkr.net",
  "rppkn.com", "rtrtr.com",
  "s0ny.net", "safe-mail.net",
  "shortmail.net", "sibmail.com",
  "sofimail.com", "spam.la",
  "spamavert.com", "spambob.net", "spambob.org",
  "spambog.com", "spambog.de", "spambog.ru",
  "spambox.us", "spamcannon.com", "spamcannon.net",
  "spamcon.org", "spamcorpse.com",
  "spamex.com", "spamfree.eu",
  "spamhole.com", "spamify.com",
  "spaminator.de", "spamkill.info",
  "spaml.com", "spaml.de",
  "spammotel.com", "spammy.host",
  "spamoff.de", "spamslicer.com",
  "spamstack.net", "spamthisplease.com",
  "spamtroll.net", "speed.1s.fr",
  "tapchicuocsong.com", "thecity.biz",
  "thisisnotmyrealemail.com", "throwam.com",
  "tilien.com", "tmail.com",
  "tmailinator.com", "toiea.com",
  "tradermail.info", "trash-mail.at",
  "trash-mail.com", "trash-mail.de",
  "trash-mail.io", "trash-mail.net",
  "trashdevil.com", "trashdevil.de",
  "trashemail.de", "trashmail.at",
  "trashmail.com", "trashmail.de",
  "trashmail.io", "trashmail.me",
  "trashmail.net", "trashmail.org",
  "trashmailer.com", "trashme.com",
  "trbvm.com", "turual.com",
  "twinmail.de", "uggsrock.com",
  "uroid.com", "us.af",
  "venompen.com", "veryrealemail.com",
  "viditag.com", "viewcastmedia.com",
  "viewcastmedia.net", "viewcastmedia.org",
  "wegwerfmail.de", "wegwerfmail.net",
  "wegwerfmail.org", "wilemail.com",
  "willselfdestruct.com", "winemaven.info",
  "wuzup.net", "wuzupmail.net",
  "www.e4ward.com", "www.mailinator.com",
  "xagloo.com", "xemaps.com",
  "xents.com", "xmaily.com",
  "xoxy.net", "yomail.info",
  "yopmail.com", "yopmail.fr",
  "youmail.ga", "ypmail.webarnak.fr.eu.org",
  "yuurok.com", "z1p.biz",
  "za.com", "zebins.com",
  "zebins.eu", "zehnminuten.de",
  "zippymail.info", "zoaxe.com",
  "zoemail.com", "zoemail.net",
  "zoemail.org", "zomg.info",
]);

export default function disposable_domain(domain, context) {
  const isDisposable = DISPOSABLE_DOMAINS.has(domain.toLowerCase());
  if (isDisposable) {
    context.flags = context.flags || [];
    context.flags.push({
      code:       "DISPOSABLE_DOMAIN",
      message:    "Email domain is a known disposable/temporary mail service",
      confidence: 0.97,
      risk:       "high",
    });
  }
  return isDisposable;
}
